version: '3.8'

services:
  api:
    build: .
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://root:MinhaSenhaForte123!@mongodb:27017/db_task_tarefas?authSource=admin
      - PORT=4000
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:6
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=MinhaSenhaForte123!
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
